# builder image
FROM golang:1.14-alpine

RUN apk update;\
    apk add git;

COPY patch /home
COPY scripts /home
WORKDIR /home

# Install flogo cli
RUN go get -u github.com/project-flogo/cli/...;\
    cp mod.go /go/src/github.com/project-flogo/cli/util/;\
    cd /go/src/github.com/project-flogo/cli;\
    go install ./...;